version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:16.3
    ports:
      - "55432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-shoply-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0 
    container_name: redis
    hostname: redis
    ports:
      - "36379:6379"  # Expose Redis on port 6379
    volumes:
      - redis-shoply-data:/data

volumes:
  pg-shoply-data:
  redis-shoply-data: